用户指南
--------

这部分文档是比较松散的，首先介绍了 Flask 的一些背景材料，
然后专注于一步一步地说明如何使用 Flask 进行 Web 开发。

.. toctree::
   :maxdepth: 2

   foreword
   advanced_foreword
   installation
   quickstart
   tutorial/index
   templating
   testing
   errorhandling
   logging
   config
   signals
   views
   appcontext
   reqcontext
   blueprints
   extensions
   cli
   server
   shell
   patterns/index
   deploying/index
   becomingbig

API 参考
-------------

这部分文档详细说明某个函数、类或方法。

.. toctree::
   :maxdepth: 2

   api

其他材料
----------------

这部分文档包括：设计要点、法律信息和变动记录。

.. toctree::
   :maxdepth: 2

   design
   htmlfaq
   security
   unicode
   extensiondev
   styleguide
   upgrading
   changelog
   license
   contributing
